DB_HOST = "aws-0-eu-west-3.pooler.supabase.com"
DB_PORT = "6543"
DB_NAME = "postgres"
DB_USER = "postgres.kumqhytmymzmbywlwepz"
DB_POOL_MODE = "transaction"
DB_PASSWORD = "12345678"
CONNECTION_STRING = postgresql://postgres.kumqhytmymzmbywlwepz:12345678@aws-0-eu-west-3.pooler.supabase.com:6543/postgres
TMDB_API_KEY = 5d603ec4bd433ee159af77e58efdc97d 
TOGETHER_AI_API_KEY = 15743d42f5e86ed678d7537a5dc5d07e9c4f44892f4a25e2794c1a68d54c0981